spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cvw643_test_mysql?useSSL=false&autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # have to set this, or engine MYISAM will be used
    open-in-view: false
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace # show binding parameter value.